name: JWT

inputs:
  algorithm:
    default: HS256
    description: (Encode) Signing algorithm for encoding a new JWT.
  fail-on-unverified:
    default: false
    description: (Decode) Fail if the token signing cannot be verified.
  headers:
    default: |
      alg: ${ALGORITHM}
      typ: JWT
    description: (Encode) Header jq template for encoding a new JWT (JSON or YAML).
  payload:
    description: (Encode) Payload data structure for encoding a new JWT (JSON or YAML).
    required: false
  secret:
    description: (Decode/Encode) (Optional) Secret used to sign or verify a signed token.
    required: false
  token:
    description: (Decode/Encode) JWT token that will be decoded & verified.
    required: false

outputs:
  algorithm:
    description: Signing algorithm.
    value: ${{ fromJSON(steps.decode.outputs.json).algorithm }}
  headers:
    description: Decoded headers in JSON.
    value: ${{ toJSON(fromJSON(steps.decode.outputs.json).headers) }}
  json:
    description: Decoded token object in JSON format.
    value: ${{ steps.decode.outputs.json }}
  payload:
    description: Decoded payload in JSON.
    value: ${{ toJSON(fromJSON(steps.decode.outputs.json).payload) }}
  token:
    description: Encoded & optionally signed token.
    value: ${{ fromJSON(steps.decode.outputs.json).token }}
  verified:
    description: Boolean-as-string ("true" / "false") indicating if the token is verified.
    value:  ${{ fromJSON(steps.decode.outputs.json).verified }}

runs:
  using: composite
  steps:
    - if: env.ACTIONS_STEP_DEBUG == 'true'
      run: |
        # JWT - Debug
        echo ::group::Debug - utility versions
        yq --version
        jq --version
        openssl version
        echo ::endgroup::
      shell: bash

    - env:
        ALGORITHM: ${{ inputs.algorithm }}
        HEADERS: ${{ inputs.headers }}
        JQ_LIB_PATH: ${{ github.action_path }}
        PAYLOAD: ${{ inputs.payload }}
        SECRET: ${{ inputs.secret }}
      id: encode
      if: inputs.payload != ''
      run: |
        # JWT - Encode Token
        HEADERS=$(yq -o json --expression 'with_entries(.value |= envsubst)' <<<"${HEADERS}" | jq -c)
        PAYLOAD=$(yq -o json <<<"${PAYLOAD}" | jq -c)
        if '${{ env.ACTIONS_STEP_DEBUG == 'true' && 'true' || 'false' }}' ; then
          echo -e "::group::Debug - headers\n${HEADERS}\n::endgroup::"
          echo -e "::group::Debug - payload\n${PAYLOAD}\n::endgroup::"
        fi
        TOKEN_UNSIGNED=$(
          jq -n -r -L "$JQ_LIB_PATH" \
            --arg headers "$HEADERS" \
            --arg payload "$PAYLOAD" \
            ' include "jwt";
              [($headers | url_safe_base64_encode), ($payload | url_safe_base64_encode)]
              | join(".")
            '
        )
        SIGNATURE_ARGS=()
        if '${{ inputs.SECRETS == '' && 'false' || 'true' }}' ; then 
          SIGNATURE_ARGS=(-hmac "$SECRET")
        fi
        SIGNATURE=$(
          echo -n "$TOKEN_UNSIGNED" |
            openssl dgst -binary "${SIGNATURE_ARGS[@]}" -sha256 |
            base64
        )
        jq -n -r -L "$JQ_LIB_PATH" \
          --arg token_unsigned "$TOKEN_UNSIGNED" \
          --arg signature "$SIGNATURE" \
          ' include "jwt";
            [($token_unsigned), ($signature | url_safe_encode)] 
            | join(".")
            | "token=\(.)"
          ' >>"${GITHUB_OUTPUT}"
      shell: bash

    - env:
        JQ_LIB_PATH: ${{ github.action_path }}
        TOKEN: ${{ inputs.token == '' && steps.encode.outputs.token || inputs.token }}
        SECRET: ${{ inputs.secret }}
      id: decode
      run: |
        # JWT - Decode/Verify Token
        TOKEN_UNSIGNED=$(
          jq -n -r -L "$JQ_LIB_PATH" --arg token "$TOKEN" \
            'include "jwt"; $token | decode.unsigned'
        )
        SIGNATURE_ARGS=()
        if '${{ inputs.SECRETS == '' && 'false' || 'true' }}' ; then 
          SIGNATURE_ARGS=(-hmac "$SECRET")
        fi
        SIGNATURE=$(
          echo -n "$TOKEN_UNSIGNED" |
            openssl dgst -binary "${SIGNATURE_ARGS[@]}" -sha256 |
            base64
        )
        echo 'json<<EOF' >>"${GITHUB_OUTPUT}"
        echo '::group::Decoded Token Object'
        jq -n -L "$JQ_LIB_PATH" --arg token "$TOKEN" --arg signature "$SIGNATURE" \
          'include "jwt"; $token | validate($signature)' |
          tee -a "$GITHUB_OUTPUT" |
          jq -C
        echo '::endgroup::'
        echo 'EOF' >>"${GITHUB_OUTPUT}"
      shell: bash
