name: JWT

inputs:
  algorithm:
    default: HS256
    description: (Encode) Signing algorithm for encoding a new JWT.
  fail-on-unverified:
    default: false
    description: (Decode) Fail if the token signing cannot be verified.
  headers:
    default: |
      alg: \($algorithm)
      typ: JWT
    description: (Encode) Header jq template for encoding a new JWT (JSON or YAML).
  payload:
    description: (Encode) Payload data structure for encoding a new JWT (JSON or YAML).
    required: false
  secret:
    description: (Decode/Encode) (Optional) Secret used to sign or verify a signed token.
    required: false
  token:
    description: (Decode/Encode) JWT token that will be decoded & verified.
    required: false

outputs:
  algorithm:
    description: (Encode/Decode) Signing algorithm.
    value: ${{ steps.
  headers:
    description: (Encode/Decode) Decoded headers in JSON.
    value: 
  payload:
    description: (Encode/Decode) Decoded payload in JSON.
    value: 
  token:
    description: (Encode/Decode) Encoded & optionally signed token.
    value: 
  verified:
    description: (Encode/Decode) true/false boolean-as-string indicating if the token is verified.
    value: 

runs:
  using: composite
  steps:
    # TODO set back to == to disable default debug
    - if: env.ACTIONS_STEP_DEBUG != 'true'
      run: |
        # JWT - Debug
        echo ::group::Display utility versions
        yq --version
        jq --version
        openssl version
        echo ::endgroup::
      shell: bash

    - env:
        ALGORITHM: ${{ inputs.algorithm }}
        HEADERS: ${{ inputs.headers }}
        JQ_LIB_PATH: ${{ github.action_path }}
        PAYLOAD: ${{ inputs.payload }}
        SECRET: ${{ inputs.secret }}
      id: encode
      if: inputs.payload != ''
      run: |
        # JWT - Encode Token
        HEADERS=$(yq -o json <<<"${HEADERS}" | jq -c --arg algorithm "$ALGORITHM")
        PAYLOAD=$(yq -o json <<<"${PAYLOAD}" | jq -c)
        TOKEN_UNSIGNED=$(
          jq -c -r -L "$JQ_LIB_PATH" \
            --arg headers "$HEADERS" \
            --arg payload "$PAYLOAD" \
            ' [($headers | url_safe_base64_encode), ($payload | url_safe_base64_encode)] |
              join(".")
            '
        )
        cat >>"${GITHUB_OUTPUTS}" <<_EOF_
        token<<EOF
        ${TOKEN_UNSIGNED}
        EOF
        _EOF_
      shell: bash

    - env:
        JQ_LIB_PATH: ${{ github.action_path }}
        TOKEN: ${{ inputs.token == '' && steps.encode.outputs.token || inputs.token }}
        SECRET: ${{ inputs.secret }}
      id: decode
      run: |
        # JWT - Decode/Verify Token
        echo 'token_object<<EOF' >>"${GITHUB_OUTPUTS}"
        echo '::group::Token Object'
        jq -L "$JQ_LIB_PATH" \
          ' {
              headers: (split(".")[0] | url_safe_base64_decode | fromjson),
              payload: (split(".")[1] | url_safe_base64_decode | fromjson),
            }
          ' <<<"${TOKEN}" |
          tee -a "$GITHUB_OUTPUTS" |
          jq -C .
        echo '::endgroup::'
        echo 'EOF' >>"${GITHUB_OUTPUTS}"
      shell: bash
