name: Call JWT

on:
  push:

jobs:
  Call-JWT-Action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: run-jwt-action
        name: Run JWT Action
        run: ./
        with:
          payload: |
            claim_key: claim_value

      - env:
          JWT_ACTION_OUTPUTS: ${{ toJSON(steps.run-jwt-action.outputs) }}
        name: Examine JWT Action output
        run: |
          echo ::group::JWT Action output
          jq -C . <<<"${JWT_ACTION_OUTPUTS}"
          echo ::endgroup::
