name: Test

on:
  repository_dispatch:
#    types: [trigger-workflow]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          # test/test
          jq -C . <<< '${{ toJSON(github.event.client_payload) }}'
